postgresql:
  raven:
    user: raven
    password: Raven@123
    host: localhost
    port: 5432
  xtract:
    user: xtract
    password: Xtract@123
    host: localhost
    port: 5432


mongodb:
  raven:
    user: raven
    password: Raven@123
    host: localhost
    port: 27017
  xtract:
    user: xtract
    password: Xtract@123
    host: localhost
    port: 27017